uint32_t winnie_color_smile[19 * 23] = {
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_BLACK ,COLOR_RED   ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_RED   ,COLOR_BLACK ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_BLACK ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_BLACK ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_RED   ,COLOR_RED   ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_RED   ,COLOR_RED   ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,
COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,
COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,
COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,
COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS
};

uint32_t winnie_color_nmsl[19 * 23] = {
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_BLACK ,COLOR_RED   ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_RED   ,COLOR_BLACK ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_BLACK ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_BLACK ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_RED   ,COLOR_RED   ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_RED   ,COLOR_RED   ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,
COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,
COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,
COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,
COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS
};


uint32_t winnie_color_sad[19 * 23] = {
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_CYAN,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_CYAN,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_CYAN,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_CYAN,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_BLACK ,COLOR_RED   ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_RED   ,COLOR_BLACK ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_BLACK ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_BLACK ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_RED   ,COLOR_RED   ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_RED   ,COLOR_RED   ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,
COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,
COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,
COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,
COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,
COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_BLACK ,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_ORANGE,COLOR_BLACK ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS ,COLOR_TRANS
};

Model Winnie = {
    .w = 19,
    .h = 23,
    .p = 1,
    .color = winnie_color_smile};



// uint32_t missile_color[5 * 10] = {
//     COLOR_TRANS ,COLOR_RED   ,COLOR_TRANS ,COLOR_RED   ,COLOR_TRANS ,
//     COLOR_BLACK ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_BLACK ,
//     COLOR_BLACK ,COLOR_BLACK ,COLOR_RED   ,COLOR_BLACK ,COLOR_BLACK ,
//     COLOR_TRANS ,COLOR_JUNGLE,COLOR_JUNGLE,COLOR_JUNGLE,COLOR_TRANS ,
//     COLOR_TRANS ,COLOR_JUNGLE,COLOR_JUNGLE,COLOR_JUNGLE,COLOR_TRANS ,
//     COLOR_TRANS ,COLOR_JUNGLE,COLOR_JUNGLE,COLOR_JUNGLE,COLOR_TRANS ,
//     COLOR_TRANS ,COLOR_JUNGLE,COLOR_JUNGLE,COLOR_JUNGLE,COLOR_TRANS ,
//     COLOR_TRANS ,COLOR_JUNGLE,COLOR_JUNGLE,COLOR_JUNGLE,COLOR_TRANS ,
//     COLOR_TRANS ,COLOR_GRAY  ,COLOR_BLACK ,COLOR_GRAY  ,COLOR_TRANS ,
//     COLOR_TRANS ,COLOR_TRANS ,COLOR_GRAY  ,COLOR_TRANS ,COLOR_TRANS
// };

uint32_t missile_color[5 * 10] = {
    COLOR_TRANS ,COLOR_TRANS ,COLOR_GRAY  ,COLOR_TRANS ,COLOR_TRANS ,
    COLOR_TRANS ,COLOR_GRAY  ,COLOR_BLACK ,COLOR_GRAY  ,COLOR_TRANS ,
    COLOR_TRANS ,COLOR_JUNGLE,COLOR_JUNGLE,COLOR_JUNGLE,COLOR_TRANS ,
    COLOR_TRANS ,COLOR_JUNGLE,COLOR_JUNGLE,COLOR_JUNGLE,COLOR_TRANS ,
    COLOR_TRANS ,COLOR_JUNGLE,COLOR_JUNGLE,COLOR_JUNGLE,COLOR_TRANS ,
    COLOR_TRANS ,COLOR_JUNGLE,COLOR_JUNGLE,COLOR_JUNGLE,COLOR_TRANS ,
    COLOR_TRANS ,COLOR_JUNGLE,COLOR_JUNGLE,COLOR_JUNGLE,COLOR_TRANS ,
    COLOR_BLACK ,COLOR_BLACK ,COLOR_RED   ,COLOR_BLACK ,COLOR_BLACK ,
    COLOR_BLACK ,COLOR_RED   ,COLOR_RED   ,COLOR_RED   ,COLOR_BLACK ,
    COLOR_TRANS ,COLOR_RED   ,COLOR_TRANS ,COLOR_RED   ,COLOR_TRANS
};

Model Missile = {
    .w = 5,
    .h = 10,
    .p = 1,
    .color = missile_color
};

uint32_t frog_color[16 * 16] = {
    COLOR_WHITE ,COLOR_WHITE ,COLOR_WHITE ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_WHITE ,COLOR_WHITE ,COLOR_WHITE ,COLOR_WHITE ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_WHITE ,COLOR_WHITE ,COLOR_WHITE ,
    COLOR_WHITE ,COLOR_WHITE ,COLOR_BLACK ,COLOR_DGREEN,COLOR_SGREEN,COLOR_SGREEN,COLOR_BLACK ,COLOR_WHITE ,COLOR_WHITE ,COLOR_BLACK ,COLOR_SGREEN,COLOR_SGREEN,COLOR_DGREEN,COLOR_BLACK ,COLOR_WHITE ,COLOR_WHITE ,
    COLOR_WHITE ,COLOR_WHITE ,COLOR_BLACK ,COLOR_DGREEN,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_DGREEN,COLOR_BLACK ,COLOR_WHITE ,COLOR_WHITE ,
    COLOR_WHITE ,COLOR_BLACK ,COLOR_BLACK ,COLOR_DGREEN,COLOR_BLACK ,COLOR_BLACK ,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_BLACK ,COLOR_BLACK ,COLOR_DGREEN,COLOR_BLACK ,COLOR_BLACK ,COLOR_WHITE ,
    COLOR_BLACK ,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_SGREEN,COLOR_SGREEN,COLOR_SGREEN,COLOR_SGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_BLACK ,
    COLOR_BLACK ,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_SGREEN,COLOR_SGREEN,COLOR_BLACK ,COLOR_SGREEN,COLOR_SGREEN,COLOR_BLACK ,COLOR_SGREEN,COLOR_SGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_BLACK ,
    COLOR_BLACK ,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_SGREEN,COLOR_SGREEN,COLOR_SGREEN,COLOR_SGREEN,COLOR_SGREEN,COLOR_SGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_BLACK ,
    COLOR_WHITE ,COLOR_BLACK ,COLOR_BLACK ,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_BLACK ,COLOR_BLACK ,COLOR_WHITE ,
    COLOR_WHITE ,COLOR_WHITE ,COLOR_WHITE ,COLOR_BLACK ,COLOR_BLACK ,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_BLACK ,COLOR_BLACK ,COLOR_WHITE ,COLOR_WHITE ,COLOR_WHITE ,
    COLOR_WHITE ,COLOR_BLACK ,COLOR_BLACK ,COLOR_WHITE ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_WHITE ,COLOR_BLACK ,COLOR_BLACK ,COLOR_WHITE ,
    COLOR_BLACK ,COLOR_SGREEN,COLOR_DGREEN,COLOR_BLACK ,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_BLACK ,COLOR_DGREEN,COLOR_SGREEN,COLOR_BLACK ,
    COLOR_BLACK ,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_BLACK ,COLOR_DGREEN,COLOR_BLACK ,COLOR_DGREEN,COLOR_DGREEN,COLOR_BLACK ,COLOR_DGREEN,COLOR_BLACK ,COLOR_DGREEN,COLOR_DGREEN,COLOR_DGREEN,COLOR_BLACK ,
    COLOR_BLACK ,COLOR_DGREEN,COLOR_BLACK ,COLOR_DGREEN,COLOR_BLACK ,COLOR_DGREEN,COLOR_BLACK ,COLOR_SGREEN,COLOR_SGREEN,COLOR_BLACK ,COLOR_DGREEN,COLOR_BLACK ,COLOR_DGREEN,COLOR_BLACK ,COLOR_DGREEN,COLOR_BLACK ,
    COLOR_WHITE ,COLOR_BLACK ,COLOR_DGREEN,COLOR_BLACK ,COLOR_BLACK ,COLOR_DGREEN,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_DGREEN,COLOR_BLACK ,COLOR_BLACK ,COLOR_DGREEN,COLOR_BLACK ,COLOR_WHITE ,
    COLOR_WHITE ,COLOR_WHITE ,COLOR_BLACK ,COLOR_DGREEN,COLOR_BLACK ,COLOR_SGREEN,COLOR_SGREEN,COLOR_BLACK ,COLOR_BLACK ,COLOR_SGREEN,COLOR_SGREEN,COLOR_BLACK ,COLOR_DGREEN,COLOR_BLACK ,COLOR_WHITE ,COLOR_WHITE ,
    COLOR_WHITE ,COLOR_WHITE ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_BLACK ,COLOR_WHITE ,COLOR_WHITE
};

Model Frog = {
    .w = 16,
    .h = 16,
    .p = 1,
    .color = frog_color
};

uint32_t heart_color[11 * 10] = {
    COLOR_TRANS,COLOR_TRANS,COLOR_BLACK,COLOR_BLACK,COLOR_TRANS,COLOR_TRANS,COLOR_TRANS,COLOR_BLACK,COLOR_BLACK,COLOR_TRANS,COLOR_TRANS,
    COLOR_TRANS,COLOR_BLACK,COLOR_RED  ,COLOR_RED  ,COLOR_BLACK,COLOR_TRANS,COLOR_BLACK,COLOR_RED  ,COLOR_RED  ,COLOR_BLACK,COLOR_TRANS,
    COLOR_BLACK,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_BLACK,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_BLACK,
    COLOR_BLACK,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_BLACK,
    COLOR_BLACK,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_BLACK,
    COLOR_TRANS,COLOR_BLACK,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_BLACK,COLOR_TRANS,
    COLOR_TRANS,COLOR_TRANS,COLOR_BLACK,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_BLACK,COLOR_TRANS,COLOR_TRANS,
    COLOR_TRANS,COLOR_TRANS,COLOR_TRANS,COLOR_BLACK,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_BLACK,COLOR_TRANS,COLOR_TRANS,COLOR_TRANS,
    COLOR_TRANS,COLOR_TRANS,COLOR_TRANS,COLOR_TRANS,COLOR_BLACK,COLOR_RED  ,COLOR_BLACK,COLOR_TRANS,COLOR_TRANS,COLOR_TRANS,COLOR_TRANS,
    COLOR_TRANS,COLOR_TRANS,COLOR_TRANS,COLOR_TRANS,COLOR_TRANS,COLOR_BLACK,COLOR_TRANS,COLOR_TRANS,COLOR_TRANS,COLOR_TRANS,COLOR_TRANS
};

Model Heart = {
    .w = 11,
    .h = 10,
    .p = 1,
    .color = heart_color
};

uint32_t honey_color[7 * 7] = {
    COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,
    COLOR_TRANS,COLOR_BROWN,COLOR_TRANS,COLOR_TRANS,COLOR_TRANS,COLOR_BROWN,COLOR_TRANS,
    COLOR_TRANS,COLOR_BROWN,COLOR_HONEY,COLOR_HONEY,COLOR_HONEY,COLOR_BROWN,COLOR_TRANS,
    COLOR_BROWN,COLOR_HONEY,COLOR_TRANS,COLOR_HONEY,COLOR_HONEY,COLOR_HONEY,COLOR_BROWN,
    COLOR_BROWN,COLOR_HONEY,COLOR_TRANS,COLOR_HONEY,COLOR_HONEY,COLOR_HONEY,COLOR_BROWN,
    COLOR_BROWN,COLOR_HONEY,COLOR_HONEY,COLOR_TRANS,COLOR_HONEY,COLOR_HONEY,COLOR_BROWN,
    COLOR_TRANS,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_BROWN,COLOR_TRANS
};

Model Honey = {
    .w = 7,
    .h = 7,
    .p = 2,
    .color = honey_color
};

uint32_t nukeBtn_color_on[12 * 12] = {
    COLOR_TRANS,COLOR_TRANS,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_TRANS,COLOR_TRANS,
    COLOR_TRANS,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_TRANS,
    COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,
    COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_BLACK,COLOR_BLACK,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,
    COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,
    COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_BLACK,COLOR_BLACK,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,
    COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_BLACK,COLOR_BLACK,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,
    COLOR_YELLO,COLOR_YELLO,COLOR_BLACK,COLOR_BLACK,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_BLACK,COLOR_BLACK,COLOR_YELLO,COLOR_YELLO,
    COLOR_YELLO,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_YELLO,
    COLOR_YELLO,COLOR_BLACK,COLOR_BLACK,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_BLACK,COLOR_BLACK,COLOR_YELLO,
    COLOR_TRANS,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_TRANS,
    COLOR_TRANS,COLOR_TRANS,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_YELLO,COLOR_TRANS,COLOR_TRANS
};

uint32_t nukeBtn_color_off[12 * 12] = {
    COLOR_TRANS,COLOR_TRANS,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_TRANS,COLOR_TRANS,
    COLOR_TRANS,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_TRANS,
    COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,
    COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_BLACK,COLOR_BLACK,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,
    COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,
    COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_BLACK,COLOR_BLACK,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,
    COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_BLACK,COLOR_BLACK,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,
    COLOR_RED  ,COLOR_RED  ,COLOR_BLACK,COLOR_BLACK,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_BLACK,COLOR_BLACK,COLOR_RED  ,COLOR_RED  ,
    COLOR_RED  ,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_RED  ,
    COLOR_RED  ,COLOR_BLACK,COLOR_BLACK,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_BLACK,COLOR_BLACK,COLOR_RED  ,
    COLOR_TRANS,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_TRANS,
    COLOR_TRANS,COLOR_TRANS,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_RED  ,COLOR_TRANS,COLOR_TRANS
};

Model NukeBtn = {
    .w = 12,
    .h = 12,
    .p = 1,
    .color = nukeBtn_color_on
};